global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nextcloud_exporter'
    static_configs:
      - targets: ['nextcloud_exporter:9205']
